apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enterprise-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: enterprise-backend

  namespaceSelector:
    matchNames:
      - enterprise

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
