trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'enterprise-backend'
  dockerRegistryServiceConnection: 'ragulm175acr'
  dockerfilePath: 'backend/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- checkout: self

- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: backend/Dockerfile
    containerRegistry: $(dockerRegistryServiceConnection)
    buildContext: backend
    tags: |
      $(tag)
      latest
